### ISSUE TITLE
http://1u.ms/log is broken?

### ISSUE THREAD

**Issue by mschwager** [neex/1u.ms#2]
Hi!

First off, thank you for this great project, and running the live service. It's very helpful for testing DNS issues.

I was reading through [the main docs](http://1u.ms/), and it references `http://1u.ms/log`. When I visit that URL or `curl` it nothing appears to happen. Am I missing something?

**Comment by neex** [comment]
Hi!

Do you see anything in the terminal when running `curl http://1u.ms/log`?

I guess the cause of the misunderstanding might be that the URL somewhat violates HTTP protocol: it never finishes loading. It is similar to pre-websocket polling techniques. Thus, opening it in a browser does not make sense.

The intended usage is like this:
1. You run `curl http://1u.ms/log?grep=...` in one terminal window and keep it running.
2. You do your experiments while checking if something appeared in the first terminal.

The whole idea is to simulate `tail -f /var/log/something.log`, which is very handy during SSRF testing.

Please check if you still have any problems. If you can suggest any particular functionality for inspecting logs (or otherwise), let me know)

**Comment by mschwager** [comment]
Hey, thanks for the quick response.

Weird, I just tested out both `curl http://1u.ms/log` and using the `grep` parameter and it's working now! I must've been having some intermittent issues yesterday. Thanks for the help!
